Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  CountComments: false
  Max: 15

Naming/FileName:
  Exclude:
    - doorman-bot.rb

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
